stages:
  - test
  - build

test:
  image: harbor.ulbricht.casa/proxy/library/node:latest
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run build

docker-build:
  image: harbor.ulbricht.casa/proxy/library/docker:dind
  stage: build
  before_script:
    - docker login -u "$HARBOR_USER" -p "$HARBOR_PASSWORD" harbor.ulbricht.casa
  script:
    - docker build --pull -t "harbor.ulbricht.casa/jinya/jinya-site:2.0.${CI_PIPELINE_IID}" -f ./Dockerfile .
    - docker tag "harbor.ulbricht.casa/jinya/jinya-site:2.0.${CI_PIPELINE_IID}" "harbor.ulbricht.casa/jinya/jinya-site:latest"
    - docker push "harbor.ulbricht.casa/jinya/jinya-site:2.0.${CI_PIPELINE_IID}"
    - docker push "harbor.ulbricht.casa/jinya/jinya-site:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile
