stages:
  - test
  - deploy

test:
  image: harbor.ulbricht.casa/proxy/library/node:latest
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run build

docker-build:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [""]
  before_script:
    - echo $KANIKO_DOCKERHUB_AND_HARBOR > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "harbor.ulbricht.casa/jinya/jinya-site:2.0.${CI_PIPELINE_IID}"
      --destination "harbor.ulbricht.casa/jinya/jinya-site:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile
