# Site settings
title: Jinya Gallery CMS
description: The Jinya Gallery CMS is the Content Management System for artists
baseurl: "https://cms.jinya.de" # the subpath of your site, e.g. /blog

exclude:
- package.json
- src
- node_modules
- yarn.lock
- gulpfile.js
- README.md
- LICENSE.txt
